### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by mareks77** [rhodium45/crypto_module#1]
Sometimes fails upon execution with this error message

`thread 'main' panicked at 'Could not read json: Inner { kind:
ne: 1, column: 1)), url: None }', libcore/result.rs:1009:5
note: Run with "RUST_BACKTRACE=1" for a backtrace.`

**Comment by rhodium45** [comment]
Hey, sorry for the late answer. I noticed the same behavoir when I close my notebook lid and open it again. Usually I just reload i3 but I will get to it.

**Comment by rhodium45** [comment]
@nephius I improved the error handling in the meanwhile. It only happens when the module tries to fetch crypto data and there's no internet connection to perform the request. Hope you'll enjoy the module more from now on. Sorry for the late fix!
